def motif_search(seq, motif):
    motifsFound = [];
    
    for i in range(0, len(seq)-len(motif)+1):
        if (seq[i: i + len(motif)] == motif) :
            motifsFound.append(i+1)

    for hits in motifsFound:
        print(str(hits) + " ", end='')
    return;





dna_sequence = "GTCACCACGCAATTCTGCAATTCGGGCAATTCGCAATTCAGGCAATTCTGGCTGCAATTCAAGCAATTCGCAATTCACCCGCAATTCTGCAATTCAGTTGCAATTCAGGTCTGCAATTCGCAATTCATTATGGGCAATTCGGGCAATTCTCGCAATTCGCAATTCTAGGCAATTCCGCAATTCGCAACAGCAATTCGCAATTCGCAATTCGGTGCAATTCTAGCAATTCGGCAATTCGCAATTCACAGCTGCAATTCGCAATTCGCAATTCAATTGCAATTCTGGCAATTCCGCAATTCCCTGCAATTCAGCAATTCTGAGTTGCTCGCAATTCCGTGTGGCAATTCGCAATTCCTTAGCAATTCCGAGAAAGCAATTCGCAATTCAGCAATTCTCCGTGGCAATTCCTGCAATTCGCGACGCAATTCGCTGGCAATTCCGCAATTCGCAATTCGCAATTCCGCAATTCTAGCTCGCAATTCCCCGGCAATTCCAGCAATTCAGAGCAATTCGCAGCAATTCCGGCAATTCTCGCAATTCCGCAATTCGCAATTCGCAATTCAGAGAGCAATTCAGCAATTCGCAATTCGGGTAGGCAATTCGAGCAATTCGCAATTCCTCAATTGCAATTCTGCAATTCGGCAATTCGCAATTCTATCGCAATTCCGATTCGCGCAATTCGAGCAATTCGGGCAATTCGCAATTCGAACATGGCAATTCTATTGCAATTCGCAATTCGCAATTCGCAATTCGCTATGGCAATTCAAGCAATTCGCTTTCAAGCAATTCGGCAATTCAGCAATTCGGA"
motif_sequence = "GCAATTCGC"
motif_search(dna_sequence, motif_sequence)